version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    container_name: rabbitmb
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - node_qeue_nw
  store:
    build: ./store
    container_name: store
    ports:
      - 3040:3040
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - node_qeue_nw
  invoice:
    build: ./invoice
    container_name: invoice
    ports:
      - 3030:3030
    depends_on:
      - store
    networks:
      - node_qeue_nw
networks:
  node_qeue_nw:
    driver: bridge
