version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    container_name: rabbitmb
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - node_qeue_nw
  store:
    build: ./store
    env_file:
      - ./store/.env
    container_name: store
    ports:
      - 3040:3040
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - node_qeue_nw
  invoice:
    build: ./invoice
    env_file:
      - ./invoice/.env
    container_name: invoice
    ports:
      - 3030:3030
    depends_on:
      - store
    networks:
      - node_qeue_nw
  stock:
    build: ./stock
    env_file:
      - ./stock/.env
    container_name: stock
    ports:
      - 3050:3050
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - node_qeue_nw
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - node_qeue_nw
networks:
  node_qeue_nw:
    driver: bridge
